"""Sensitivity of the C1 comparison to the pre-registered late rule (descriptive; not part of the pre-registration).

Usage: sensitivity.py [--split test|val] [--out paper/tables/sensitivity.tex]
The pre-registered rule scores a run that overruns its budget by more than 10% + 0.25 s by the best plan its trace had
reached at the budget, or as a failure (makespan 200) if it keeps no trace, which is the case for RL(s.N) and CTAS-D.
A policy rollout that is still running at the deadline therefore turns RL's whole instance into a failure. This
script re-scores every late run by the final plan it returned, which is generous to the late method, and reports how
the C1 ratios ALNS / competitor at B1 on 8 cores change. Writes number macros (\\LateRL, \\SensRLgainlo, ...).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(Path(__file__).resolve().parent))
import anytime as at
from make_tables import COMPETITORS, SETTINGS, label


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--split", choices=["test", "val"], default="test")
    ap.add_argument("--out", type=Path, default=Path(__file__).resolve().parents[1] / "tables" / "sensitivity.tex")
    args = ap.parse_args()
    at.SPLIT = args.split
    at.OUT = at.RUNS_DIR / ("anytime_test" if args.split == "test" else "anytime_c1")
    at.GRID = at.grid_test if args.split == "test" else at.grid_c1
    at.LATE_RULE = "score"
    late = {k: 0 for k, _ in COMPETITORS} | {"ALNS2": 0}
    gains: dict[str, list[float]] = {k: [] for k, _ in COMPETITORS}
    print(f"{'setting':18s} {'competitor':10s} {'n':>3s} {'late':>4s} {'prereg':>7s} {'final':>7s}")
    for name in SETTINGS:
        rows = at.load_rows(name)
        ours = rows.get(("ALNS2", 8, "B1"), {})
        late["ALNS2"] += sum(at.late(r) for r in ours.values())
        for key, _ in COMPETITORS:
            other = rows.get((key, 8, "B1"), {})
            common = sorted(set(ours) & set(other))
            if not common:
                continue
            n_late = sum(at.late(other[i]) for i in common)
            late[key] += n_late
            prereg = np.mean([at.at_budget(ours[i]) / at.at_budget(other[i]) for i in common])
            final = np.mean([at.at_budget(ours[i]) / at.score(other[i]) for i in common])
            gains[key].append(100 * (1 - final))
            print(f"{label(name):18s} {key:10s} {len(common):3d} {n_late:4d} {prereg:7.3f} {final:7.3f}")

    def macro(name: str, value: str) -> str:
        return f"\\newcommand{{\\{name}}}{{{value}}}"

    lines = [f"% generated by paper/tools/sensitivity.py --split {args.split}",
             macro("LateRL", str(late["RL"])), macro("LateALNS", str(late["ALNS2"])),
             macro("LateOther", str(sum(v for k, v in late.items() if k not in ("RL", "ALNS2"))))]
    for key, _ in COMPETITORS:
        g = gains[key]
        m = key.lower()
        lines += [macro(f"Sens{m}gainlo", f"{min(g):.1f}" if g else "--"),
                  macro(f"Sens{m}gainhi", f"{max(g):.1f}" if g else "--")]
    args.out.write_text("\n".join(lines) + "\n")
    print(f"late runs at B1 on 8 cores: {late}; wrote {args.out}")


if __name__ == "__main__":
    main()
